project: 
  type: website

website:
  title: "Projet Volant"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - volant.qmd
      - href: nested/nested_file.qmd
        text: nested

format:
  html:
    theme: darksly
    #css: styles.css
    toc: true